version: '3'
services:
  nginx:
    build: ./web
    ports: 
    - "80:80"

  postgres:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=notTheRootUser
      - POSTGRES_PASSWORD=notTheRootPassword

  drinkspiration:
    build: .
    ports:
      - "8080:8080"
