version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=notTheRootUser
      - POSTGRES_PASSWORD=notTheRootPassword
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

  drinkspiration:
    build: .
    ports:
      - "8080:8080"
